spring.application.name=user-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/streamingBD
spring.datasource.username=postgres
spring.datasource.password=Postgres2026.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true